### ISSUE TITLE
What types of challenges can be submitted? 

### ISSUE THREAD

**Issue by alizaincodes** [mmujtabah/CodingChallenges#22]
Hi there 👋🏻 

I want to ask that what types of challenges can be submitted?

First, you have already mentioned that we can create contributions in `Python`, `Javascript`, `C++` and `Java` languages. 

I want to ask that if we submit a web app like in python we use django and flask to make these. 

Can we submit a whole web app project?

**Comment by mmujtabah** [comment]
Any type of challenge is welcome as long as it provides value to others. The programming languages listed are just examples you are free to use any language you prefer. Submissions can range from a single file or script to a full project, including web apps built with frameworks like Django or Flask. For project submissions, please create a directory with a name following the pattern `project_<your_project_name>` to keep things organized. I appreciate all contributions that enhance the repository!

**Comment by alizaincodes** [comment]
@mmujtabah Thanks 👍🏻 

Can you update README.md for this? 
This will let everyone know what type of contributions they can make.

**Comment by mmujtabah** [comment]
> @mmujtabah Thanks 👍🏻
> 
> Can you update README.md for this? This will let everyone know what type of contributions they can make.

Done

**Comment by alizaincodes** [comment]
Okay now you can close this issue.
