### ISSUE TITLE
How to proceed?

### ISSUE THREAD

**Issue by RampageousRJ** [mmujtabah/CodingChallenges#3]
Hey I am a newbie open source contributor but an seasoned and equipped with data structures and algorithms. I am not able to understand what is to be done in this repository, I am open to help but kindly explain what help is required here.

**Comment by RampageousRJ** [comment]
Basically, are we reuqired to solve the sample question itself and thats it or are we supposed to add more challeneges or something?

**Comment by mmujtabah** [comment]
- **Add new challenges**: Feel free to expand the challenge set by adding more coding problems to the challenges folder. You can create interesting, beginner-friendly or advanced challenges depending on what you'd like to contribute.

- **Provide solutions**: You can also provide solutions to the existing challenges in any programming language you're comfortable with. Just make sure to structure your contributions clearly and follow the repository's contribution guidelines.
